### ISSUE TITLE
Update for 19.3

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/dev_tools#11]
It appears that the operator would need to be updated in order to work on `19.3`. Trying to build it, I get:
```
> make
Using SciDB path /opt/scidb/19.3
"/usr/bin/g++-4.9" -pedantic -W -Wextra -Wall -Wno-variadic-macros -Wno-strict-aliasing -Wno-long-long -Wno-unused-parameter -fPIC -DSCIDB_VARIANT=1903 -O2 -DNDEBUG -std=c++14 -DCPP14 -I. -DPROJECT_ROOT="\"/opt/scidb/19.3\"" -I"/opt/scidb/19.3/3rdparty/boost/include/" -I"/opt/scidb/19.3/include" -I./extern -o Logicalinstall_github.o -c Logicalinstall_github.cpp
Logicalinstall_github.cpp:1:28: fatal error: query/Operator.h: No such file or directory
 #include "query/Operator.h"
                            ^
compilation terminated.
make: *** [libdev_tools.so] Error 1
```
